# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XAHealth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MJRefresh', '~> 3.1.12'
  
  # 集成微信(精简版0.2M)
  pod ‘UMengUShare/Social/ReducedWeChat'
  
  # 集成QQ(精简版0.5M)
  pod ‘UMengUShare/Social/ReducedQQ'
  
  # 集成新浪微博(精简版1M)
  pod ‘UMengUShare/Social/ReducedSina'
  
  # 集成短信
  pod ‘UMengUShare/Social/SMS'
  # Pods for XAHealth

end
